# Generated by Django 5.1.3 on 2024-11-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('max_uses', models.PositiveIntegerField(default=5)),
                ('uses', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
