# Generated by Django 5.1.3 on 2024-11-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='tier',
            field=models.CharField(choices=[('tier1', 'Tier 1'), ('tier2', 'Tier 2'), ('tier3', 'Tier 3'), ('tier4', 'Tier 4'), ('tier5', 'Tier 5')], default='tier1', max_length=5),
        ),
    ]
