# Generated by Django 5.1.3 on 2024-11-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0002_character_url_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='skin',
            name='url_img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
