# Generated by Django 5.1.3 on 2024-11-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0004_imagetype_url_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
            ],
        ),
    ]
