# Generated by Django 5.1.3 on 2024-11-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0007_tag_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='tags_deleted',
            field=models.ManyToManyField(related_name='specialsDel', to='generate.tag'),
        ),
        migrations.AlterField(
            model_name='special',
            name='tags_required',
            field=models.ManyToManyField(related_name='specialsAdd', to='generate.tag'),
        ),
    ]
