# Generated by Django 5.1.3 on 2024-11-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0008_special_tags_deleted_alter_special_tags_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='tags_deleted',
            field=models.ManyToManyField(blank=True, related_name='specialsDel', to='generate.tag'),
        ),
        migrations.AlterField(
            model_name='special',
            name='tags_required',
            field=models.ManyToManyField(blank=True, related_name='specialsAdd', to='generate.tag'),
        ),
    ]
