# Generated by Django 5.1.3 on 2024-12-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0009_alter_special_tags_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetype',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imagetype',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
