# Generated by Django 5.1.3 on 2024-12-07 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0010_imagetype_height_imagetype_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='pose',
            name='img_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poses', to='generate.imagetype'),
        ),
    ]
