# Generated by Django 5.1.3 on 2024-12-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0011_pose_img_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tier', models.CharField(choices=[('tier1', 'Tier 1'), ('tier2', 'Tier 2'), ('tier3', 'Tier 3'), ('tier4', 'Tier 4'), ('tier5', 'Tier 5')], default='tier5', max_length=5)),
                ('specials', models.ManyToManyField(blank=True, related_name='presets', to='generate.special')),
            ],
        ),
    ]
