# Generated by Django 5.1.3 on 2025-02-05 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0013_controlpose'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlpose',
            old_name='url',
            new_name='url_img',
        ),
    ]
