# Generated by Django 5.1.3 on 2025-02-26 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0014_rename_url_controlpose_url_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlpose',
            name='img_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posesControl', to='generate.imagetype'),
        ),
    ]
