# Generated by Django 5.1.3 on 2025-08-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0015_controlpose_img_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pose',
            name='special_disabled',
            field=models.ManyToManyField(blank=True, help_text='Specials que serán deshabilitados cuando se seleccione esta pose', related_name='disabled_in_poses', to='generate.special'),
        ),
    ]
