# Generated by Django 5.1.3 on 2025-08-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0016_pose_special_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='pose',
            name='special_enabled',
            field=models.ManyToManyField(blank=True, help_text='Specials que serán habilitados cuando se seleccione esta pose', related_name='enabled_in_poses', to='generate.special'),
        ),
    ]
